### PR TITLE
Wip/ecc

### PR DESCRIPTION
**Pull request by damageboy**
Adds a somewhate hacky and special purpose support for adding the ecc memory information that is derived from applying search filters during the scraping process rather than read the ecc data directly from the scraped data (which is impossible since it doesn't really exist)..

In other words, instead of scraping N pages directly, with this PR, the code with scrap the memory data with 4 different URL bases reflecting:
* ECC-Registered
* ECC-NonRegistered
* NoEcc-Buffered
* NoECC-Unbuffered

The 4 results "sets" are merged back, not before a fake "ecc" property is slapped on to the data classes...

Apart from this, I didn't feel like waiting for hours to accomplish the scraping, so the scraping process now uses python multiprocessing with a pool of 16 sub-processes, all process the cartesian product of all regions/parts combinations...

This where this could be improved upon (In the future):
* Detect the various filters for each product type automatically from the page itself
* Change the queries so that all filters are applied exhaustively(For example, a product with 4 applicable filters with 4 options per filter would 4^4 queries for that product)

### CODE REVIEW

**Comment by JonathanVusich** [comment]
In general, I think the changes are quite good. I would appreciate a couple of minor changes before merging though. 
1. The use of multiprocessing to scrape for the data should be optional, with the default being off. I have run into issues where my IP was blocked due to too many simultaneous requests. That is part of the reason why I had to build this scraper as a separate module in the first place. If you wish to use multiprocessing, you should do so at your own risk. :)
2. Add a few comments when you are doing your set operations. I have looked at it a little bit, and I think I understand what you are doing, but it would be nice to have those operations detailed a little more for future clarity. 
3. Try and remove single letter variables as much as possible. They are the bane of my existence. 

Otherwise, it looks good!

**Review by JonathanVusich — CHANGES_REQUESTED** [review]
In general, I think the changes are quite good. I would appreciate a couple of minor changes before merging though. 
1. The use of multiprocessing to scrape for the data should be optional, with the default being off. I have run into issues where my IP was blocked due to too many simultaneous requests. That is part of the reason why I had to build this scraper as a separate module in the first place. If you wish to use multiprocessing, you should do so at your own risk. :)
2. Add a few comments when you are doing your set operations. I have looked at it a little bit, and I think I understand what you are doing, but it would be nice to have those operations detailed a little more for future clarity. 
3. Try and remove single letter variables as much as possible. They are the bane of my existence. 

Otherwise, it looks good!

**Comment by damageboy** [comment]
I've addressed your comments, let me know what you think...

**Comment by damageboy** [comment]
BTW, once you do incorporate this, you will of course have to merge the data back and publish it while also updating the pcpartpicker api to expose the new property

**Comment by JonathanVusich** [comment]
The only changes on the API side should be the updated `Memory` class. All the API does is deserialize the data stored in this repo.

**Review by JonathanVusich — APPROVED** [review]

**Pull request merged**
